import type { MuseInstrumentDefinition } from "./types";

const ALL_ARTICULATIONS = [
  "sustain",
  "legato",
  "staccato",
  "marcato",
  "accent",
  "pizzicato",
  "tremolo",
  "swell",
] as const;

/**
 * Instrument-independent catalog. The orchestration engine only ever reasons
 * about family/range/capabilities/roles — `generalMidiProgram` and
 * `soundfontName` exist purely for the MVP General-MIDI/soundfont renderer
 * and must never leak into orchestration decisions.
 */
export const MUSE_INSTRUMENT_CATALOG: MuseInstrumentDefinition[] = [
  {
    id: "solo_violin",
    name: "Solo Violin",
    family: "strings",
    range: {
      lowMidi: 55,
      highMidi: 103,
      preferredLowMidi: 60,
      preferredHighMidi: 96,
    },
    capabilities: [...ALL_ARTICULATIONS],
    roles: ["melody", "counterMelody", "accent"],
    weight: "light",
    maxVoices: 1,
    generalMidiProgram: 40,
    soundfontName: "violin",
    channelHint: "melodic",
  },
  {
    id: "viola",
    name: "Viola",
    family: "strings",
    range: {
      lowMidi: 48,
      highMidi: 91,
      preferredLowMidi: 55,
      preferredHighMidi: 84,
    },
    capabilities: [...ALL_ARTICULATIONS],
    roles: ["harmony", "counterMelody", "chordPad"],
    weight: "light",
    maxVoices: 4,
    generalMidiProgram: 41,
    soundfontName: "viola",
    channelHint: "melodic",
  },
  {
    id: "solo_cello",
    name: "Cello",
    family: "strings",
    range: {
      lowMidi: 36,
      highMidi: 76,
      preferredLowMidi: 40,
      preferredHighMidi: 72,
    },
    capabilities: [...ALL_ARTICULATIONS],
    roles: ["counterMelody", "harmony", "bass", "melody"],
    weight: "light",
    maxVoices: 1,
    generalMidiProgram: 42,
    soundfontName: "cello",
    channelHint: "melodic",
  },
  {
    id: "double_bass",
    name: "Double Bass",
    family: "strings",
    range: {
      lowMidi: 28,
      highMidi: 67,
      preferredLowMidi: 28,
      preferredHighMidi: 55,
    },
    capabilities: [
      "sustain",
      "legato",
      "staccato",
      "marcato",
      "accent",
      "pizzicato",
      "tremolo",
    ],
    roles: ["bass"],
    weight: "medium",
    maxVoices: 1,
    generalMidiProgram: 43,
    soundfontName: "contrabass",
    channelHint: "melodic",
  },
  {
    id: "string_ensemble",
    name: "String Ensemble",
    family: "strings",
    range: {
      lowMidi: 36,
      highMidi: 96,
      preferredLowMidi: 48,
      preferredHighMidi: 84,
    },
    capabilities: [...ALL_ARTICULATIONS],
    roles: ["harmony", "chordPad", "pad", "melody", "rhythmicOstinato"],
    weight: "medium",
    maxVoices: 6,
    generalMidiProgram: 48,
    soundfontName: "string_ensemble_1",
    channelHint: "melodic",
  },
  {
    id: "orchestral_harp",
    name: "Harp",
    family: "strings",
    range: {
      lowMidi: 24,
      highMidi: 103,
      preferredLowMidi: 36,
      preferredHighMidi: 96,
    },
    capabilities: ["staccato", "legato", "accent", "tremolo", "swell"],
    roles: ["accent", "pad", "effect", "chordPad"],
    weight: "light",
    maxVoices: 4,
    generalMidiProgram: 46,
    soundfontName: "orchestral_harp",
    channelHint: "melodic",
  },
  {
    id: "flute",
    name: "Flute",
    family: "woodwinds",
    range: {
      lowMidi: 60,
      highMidi: 96,
      preferredLowMidi: 62,
      preferredHighMidi: 93,
    },
    capabilities: [
      "sustain",
      "legato",
      "staccato",
      "marcato",
      "accent",
      "swell",
      "tremolo",
    ],
    roles: ["melody", "counterMelody", "accent"],
    weight: "light",
    maxVoices: 1,
    generalMidiProgram: 73,
    soundfontName: "flute",
    channelHint: "melodic",
  },
  {
    id: "oboe",
    name: "Oboe",
    family: "woodwinds",
    range: {
      lowMidi: 58,
      highMidi: 91,
      preferredLowMidi: 60,
      preferredHighMidi: 88,
    },
    capabilities: ["sustain", "legato", "staccato", "marcato", "accent"],
    roles: ["melody", "counterMelody"],
    weight: "light",
    maxVoices: 1,
    generalMidiProgram: 68,
    soundfontName: "oboe",
    channelHint: "melodic",
  },
  {
    id: "clarinet",
    name: "Clarinet",
    family: "woodwinds",
    range: {
      lowMidi: 50,
      highMidi: 94,
      preferredLowMidi: 55,
      preferredHighMidi: 88,
    },
    capabilities: ["sustain", "legato", "staccato", "marcato", "accent"],
    roles: ["melody", "counterMelody", "harmony"],
    weight: "light",
    maxVoices: 1,
    generalMidiProgram: 71,
    soundfontName: "clarinet",
    channelHint: "melodic",
  },
  {
    id: "bassoon",
    name: "Bassoon",
    family: "woodwinds",
    range: {
      lowMidi: 34,
      highMidi: 75,
      preferredLowMidi: 36,
      preferredHighMidi: 72,
    },
    capabilities: ["sustain", "legato", "staccato", "marcato", "accent"],
    roles: ["bass", "harmony", "counterMelody"],
    weight: "light",
    maxVoices: 1,
    generalMidiProgram: 70,
    soundfontName: "bassoon",
    channelHint: "melodic",
  },
  {
    id: "french_horn",
    name: "French Horn",
    family: "brass",
    range: {
      lowMidi: 34,
      highMidi: 77,
      preferredLowMidi: 41,
      preferredHighMidi: 72,
    },
    capabilities: [
      "sustain",
      "legato",
      "staccato",
      "marcato",
      "accent",
      "swell",
    ],
    roles: ["harmony", "melody", "accent", "pad"],
    weight: "medium",
    maxVoices: 4,
    generalMidiProgram: 60,
    soundfontName: "french_horn",
    channelHint: "melodic",
  },
  {
    id: "trumpet",
    name: "Trumpet",
    family: "brass",
    range: {
      lowMidi: 54,
      highMidi: 86,
      preferredLowMidi: 60,
      preferredHighMidi: 84,
    },
    capabilities: ["sustain", "legato", "staccato", "marcato", "accent"],
    roles: ["melody", "accent", "counterMelody"],
    weight: "medium",
    maxVoices: 1,
    generalMidiProgram: 56,
    soundfontName: "trumpet",
    channelHint: "melodic",
  },
  {
    id: "trombone",
    name: "Trombone",
    family: "brass",
    range: {
      lowMidi: 40,
      highMidi: 72,
      preferredLowMidi: 45,
      preferredHighMidi: 70,
    },
    capabilities: ["sustain", "legato", "staccato", "marcato", "accent"],
    roles: ["harmony", "bass", "accent"],
    weight: "medium",
    maxVoices: 1,
    generalMidiProgram: 57,
    soundfontName: "trombone",
    channelHint: "melodic",
  },
  {
    id: "tuba",
    name: "Tuba",
    family: "brass",
    range: {
      lowMidi: 28,
      highMidi: 58,
      preferredLowMidi: 29,
      preferredHighMidi: 53,
    },
    capabilities: ["sustain", "legato", "staccato", "marcato", "accent"],
    roles: ["bass"],
    weight: "heavy",
    maxVoices: 1,
    generalMidiProgram: 58,
    soundfontName: "tuba",
    channelHint: "melodic",
  },
  {
    id: "timpani",
    name: "Timpani",
    family: "percussion",
    range: {
      lowMidi: 40,
      highMidi: 57,
      preferredLowMidi: 43,
      preferredHighMidi: 53,
    },
    capabilities: ["staccato", "marcato", "accent", "tremolo", "sustain"],
    roles: ["accent", "rhythmicOstinato"],
    weight: "medium",
    maxVoices: 2,
    generalMidiProgram: 47,
    soundfontName: "timpani",
    channelHint: "melodic",
  },
  {
    id: "orchestral_percussion",
    name: "Orchestral Percussion",
    family: "percussion",
    range: {
      lowMidi: 35,
      highMidi: 81,
      preferredLowMidi: 35,
      preferredHighMidi: 59,
    },
    capabilities: ["staccato", "accent", "marcato"],
    roles: ["percussion", "rhythmicOstinato", "accent"],
    weight: "heavy",
    maxVoices: 8,
    generalMidiProgram: 0,
    soundfontName: "percussion",
    channelHint: "percussion",
  },
  {
    id: "piano",
    name: "Piano",
    family: "keys",
    range: {
      lowMidi: 21,
      highMidi: 108,
      preferredLowMidi: 36,
      preferredHighMidi: 96,
    },
    capabilities: ["sustain", "legato", "staccato", "marcato", "accent"],
    roles: ["melody", "harmony", "chordPad", "bass", "counterMelody"],
    weight: "medium",
    maxVoices: 10,
    generalMidiProgram: 0,
    soundfontName: "acoustic_grand_piano",
    channelHint: "melodic",
  },
  {
    id: "choir_pad",
    name: "Choir Pad",
    family: "choir",
    range: {
      lowMidi: 48,
      highMidi: 84,
      preferredLowMidi: 55,
      preferredHighMidi: 79,
    },
    capabilities: ["sustain", "swell", "legato"],
    roles: ["pad", "chordPad", "harmony"],
    weight: "medium",
    maxVoices: 4,
    generalMidiProgram: 52,
    soundfontName: "choir_aahs",
    channelHint: "melodic",
  },
  {
    id: "synth_pad",
    name: "Synth Pad",
    family: "synth",
    range: {
      lowMidi: 36,
      highMidi: 96,
      preferredLowMidi: 48,
      preferredHighMidi: 84,
    },
    capabilities: ["sustain", "swell", "legato"],
    roles: ["pad", "chordPad", "effect"],
    weight: "light",
    maxVoices: 4,
    generalMidiProgram: 89,
    soundfontName: "pad_2_warm",
    channelHint: "melodic",
  },
  {
    id: "acoustic_guitar",
    name: "Acoustic Guitar",
    family: "folk",
    range: {
      lowMidi: 40,
      highMidi: 88,
      preferredLowMidi: 45,
      preferredHighMidi: 79,
    },
    capabilities: ["staccato", "legato", "accent", "pizzicato"],
    roles: ["harmony", "rhythmicOstinato", "melody"],
    weight: "light",
    maxVoices: 4,
    generalMidiProgram: 24,
    soundfontName: "acoustic_guitar_nylon",
    channelHint: "melodic",
  },
  {
    id: "orchestra_hit_fx",
    name: "Orchestra Hit",
    family: "other",
    range: {
      lowMidi: 36,
      highMidi: 84,
      preferredLowMidi: 48,
      preferredHighMidi: 72,
    },
    capabilities: ["accent", "marcato"],
    roles: ["accent", "effect"],
    weight: "heavy",
    maxVoices: 1,
    generalMidiProgram: 55,
    soundfontName: "orchestra_hit",
    channelHint: "melodic",
  },
];

export function getInstrumentById(
  id: string,
): MuseInstrumentDefinition | undefined {
  return MUSE_INSTRUMENT_CATALOG.find((i) => i.id === id);
}

export function getInstrumentsByFamily(
  family: MuseInstrumentDefinition["family"],
): MuseInstrumentDefinition[] {
  return MUSE_INSTRUMENT_CATALOG.filter((i) => i.family === family);
}

export function getInstrumentsForRole(
  role: MuseInstrumentDefinition["roles"][number],
): MuseInstrumentDefinition[] {
  return MUSE_INSTRUMENT_CATALOG.filter((i) => i.roles.includes(role));
}
